### ISSUE TITLE
Multiple labels supported?

### ISSUE THREAD

**Issue by devurandom** [wtforms/wtforms#120]
For my form I need the fields to have multiple labels – one for each language I support. This is because I used a very simple approach to i18n [1], which works very well on my small website:
```css
body.en :lang(de) {
  display: none;
}
body.de :lang(en) {
  display: none;
}
```
```html
<select id="lang" onChange="document.body.className = this.value">
  <option value="en">English</option>
  <option value="de">Deutsch</option>
</select>
…
<label for="thing" lang="en">Thing</label>
<label for="thing" lang="de">Ding</label>
<input id="thing" name="thing" type="text"/>
```

Is this somehow possible with WTForms?

[1] http://stackoverflow.com/a/13607315/1975217
